# Configuración de la aplicación
spring.application.name=practica10
spring.datasource.url=jdbc:postgresql://localhost:5432/practica10
spring.datasource.username=postgres
spring.datasource.password=1234danibnk

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=5432